
exports.makerandodeck= function()
{
    var deckarray = [
        {fulltext: 'Ayn Rando'},
        {fulltext: 'Rando Calrissian'},
        {fulltext: 'Rando Molari'},
        {fulltext: 'Rando II: First Blood'},
        {fulltext: 'Macho Man Rando Savage'},
        {fulltext: 'The Amazing James Rando'},
        {fulltext: 'Rando al\'Thor'},
        {fulltext: 'Rando Roddy Piper'},
        {fulltext: 'James Rando'},
        {fulltext: 'Mahatma Randho'},
        {fulltext: 'Cheeky Randos'},
        {fulltext: 'Rando Gate'},
        {fulltext: 'His Royal Highness, the Rando of Arg'},
        {fulltext: 'Arando The Twist'},
        {fulltext: 'Rando Giles'},
        {fulltext: 'Rando Pando'},
        {fulltext: "Rando Or Rando Not"},
        {fulltext: "RanDoLorean"},
        {fulltext: "Make It Rando"},
        {fulltext: "Theory Of Randotivity"},
        {fulltext: "Rando Encounter"},
        {fulltext: "Rando On The Run"},
        {fulltext: "Pseudo Rando"},
        {fulltext: "Rando Acts Of Violence"},
        {fulltext: "Rando Warhol"},
        {fulltext: "Yankee Doodle Rando"},
        {fulltext: "Marlon Rando"},
        {fulltext: "Fire Brando"},
        {fulltext: "Rando The Grey"},
        {fulltext: "Rando The Red Nosed Reindeer"},
        {fulltext: "Do The Fan Rando"},
        {fulltext: "The Promised Rando"},
        {fulltext: "Never-Never Rando"},
        {fulltext: "Cloud Cuckoo Rando"},
        {fulltext: "Captain Corelli's Randolin"},
        {fulltext: "Rando Chutney"},
        {fulltext: "A Cheeky Randos"},
        {fulltext: "Randora's Box"},
        {fulltext: "Kung Fu Rando"},
        {fulltext: "Randomonium"},
        {fulltext: "Susan Sarando"},
        {fulltext: "Randoori Chicken"},
        {fulltext: "RandoVision"},
        {fulltext: "John Randoe"},
        {fulltext: "Randoffish"},
        {fulltext: "AcceleRando"},
        {fulltext: "Antonio Randoras"},
        {fulltext: "Randokil"},
        {fulltext: "Randobe Acrobat"}
    ];
    return deckarray;
}

